name: Build and Deploy
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: install unzip
        run: |
          sudo apt-get update
          sudo apt-get install -qq unzip

      - name: Install
        run: yarn install

      - name: Sanity check file got created
        run: |
          cat src/generated/packsList.ts
          cat src/generated/packsList_lotr.ts

      - name: make card dir
        run: mkdir -p public/image/cards

      - name: Unzip Card Images
        run: yarn setup-images

      - name: Sanity check images
        run: |
          cd public/images/cards
          ls

      - name: Build 🔧
        run: yarn build:prod

      - name: Set current date as env variable
        run: echo "NOW::$(date +'%Y-%m-%dT%H:%M')" >> $GITHUB_ENV

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "_REPLACE_DATE_"
          replace: $NOW
          include: "build/**"
          regex: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
