name: Releases

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
